### ISSUE TITLE
Committer check failing

### ISSUE THREAD

**Issue by bootstraponline** [contributor-assistant/github-action#7]
URL to the linked Repo/Org:
https://github.com/Flank/flank/pull/621

Steps to reproduce the problem:

1. Submit a PR
2. Comment. CLA assistant reports `CLA Assistant Lite All Contributors have signed the CLA.`
3. Check fails https://github.com/Flank/flank/pull/621/checks?check_run_id=463938756

What is the expected result?
CLA check passes.

What happens instead?

- https://github.com/Flank/flank/pull/621/checks?check_run_id=463938756

```
Run cla-assistant/github-action@v1.2.0-alpha
CLA Assistant GitHub Action has started
the PR No is 621
committersAfterWhiteListCheck [
  {
    "name": "bootstraponline",
    "id": 1173057,
    "pullRequestNo": 621
  }
]
(node:2619) UnhandledPromiseRejectionWarning: HttpError: Could not create file: At least 1 approving review is required by reviewers with write access.
##[error]committers of pull request 621  has to sign the CLA
    at /home/runner/work/_actions/cla-assistant/github-action/v1.2.0-alpha/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2619) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2619) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  Complete job
```

**Comment by bootstraponline** [comment]
![image](https://user-images.githubusercontent.com/1173057/75130377-ed962a00-5682-11ea-8bea-cb943a0b664e.png)


I closed then opened the PR and now it works. This seems a bit buggy?

**Comment by ibakshay** [comment]
Hi @bootstraponline, It looks like the `master` branch is protected and hence, CLA Action is not able to create a signature file where the contributors signatures will be stored. An easy workaround is to change the `branch`input in the CLA workflow file to another branch which is not protected for storing the contributors signatures.  

![Screenshot 2020-02-24 at 11 25 36](https://user-images.githubusercontent.com/33329946/75145092-9cc11880-56f8-11ea-926f-32a36fa236e3.png)


I am sorry, I didn't cover this `branch protection` use-case and that's why this action was behaving funny 😄.

**Comment by Writhe** [comment]
Hi @ibakshay,

I think there might be an issue with error handling for the Promise.all, [here](https://github.com/cla-assistant/github-action/blob/fae08470efc6e12802692077a0d1858f3414b9ca/src/checkcla.ts#L93). Since the resulting promise is not `await`ed (not is its `.catch` method called), the condition at line 94 is always true and line 98 is - in effect - unreachable.

**Comment by ibakshay** [comment]
Hi, @Writhe Thank you very much for pointing out, it will definitely help us for debugging.
I have used Promise.all rather than classic async/await to make parallel API calls where ever possible to speed up the process.  
Also, Feel free to raise a Pull Request to fix this error handling if you like to  😄.

**Comment by Writhe** [comment]
Done.

Ah, I didn't suggest `await`ing the promises sequentially. What I meant was the output of Promise.all() - which is a promise itself - should be `await`ed or otherwise handled in case any of the promises gets rejected. I should've phrased it better.
